lane :test do
  xliff_en_gen(xcodeproj:"./test/test.xcodeproj",localizable:"./test/test/Base.lproj/", keepArtifacts: false)

  puts "output: "+lane_context[SharedValues::XE_XLIFF_LOCATION]

  puts export_xliff(xcodeproj:"./test/test.xcodeproj")

  puts Actions.lane_context[SharedValues::XE_XLIFF_LOCATION]
end
